/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@aucegypt.edu)

	This file is auto-generated by wrapper_gen.py

	Permission is hereby granted, free of charge, to any person obtaining
	a copy of this software and associated documentation files (the
	"Software"), to deal in the Software without restriction, including
	without limitation the rights to use, copy, modify, merge, publish,
	distribute, sublicense, and/or sell copies of the Software, and to
	permit persons to whom the Software is furnished to do so, subject to
	the following conditions:

	The above copyright notice and this permission notice shall be
	included in all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
	MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
	NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
	OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
	WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

*/


#define EF_TCC32_BASE				0x00000000

#define	EF_TCC32_TIMER_REG_ADDR		(EF_TCC32_BASE+0x0)
#define	EF_TCC32_PERIOD_REG_ADDR		(EF_TCC32_BASE+0x4)
#define	EF_TCC32_COUNTER_REG_ADDR		(EF_TCC32_BASE+0x8)
#define	EF_TCC32_COUNTER_MATCH_REG_ADDR		(EF_TCC32_BASE+0xc)
#define	EF_TCC32_CONTROL_REG_ADDR		(EF_TCC32_BASE+0x10)
#define	EF_TCC32_ICR_REG_ADDR		(EF_TCC32_BASE+0xf00)
#define	EF_TCC32_RIS_REG_ADDR		(EF_TCC32_BASE+0xf04)
#define	EF_TCC32_IM_REG_ADDR		(EF_TCC32_BASE+0xf08)
#define	EF_TCC32_MIS_REG_ADDR		(EF_TCC32_BASE+0xf0c)

#define EF_TCC32_CONTROL_REG_EN		0
#define EF_TCC32_CONTROL_REG_EN_LEN	1
#define EF_TCC32_CONTROL_REG_TIMER_EN		1
#define EF_TCC32_CONTROL_REG_TIMER_EN_LEN	1
#define EF_TCC32_CONTROL_REG_CP_EN		3
#define EF_TCC32_CONTROL_REG_CP_EN_LEN	1
#define EF_TCC32_CONTROL_REG_CLK_SRC		8
#define EF_TCC32_CONTROL_REG_CLK_SRC_LEN	4
#define EF_TCC32_CONTROL_REG_UP_DOWN		16
#define EF_TCC32_CONTROL_REG_UP_DOWN_LEN	1
#define EF_TCC32_CONTROL_REG_ONE_SHOT		17
#define EF_TCC32_CONTROL_REG_ONE_SHOT_LEN	1
#define EF_TCC32_CONTROL_REG_CP_EVENT		24
#define EF_TCC32_CONTROL_REG_CP_EVENT_LEN	2
#define INT_TO_FLAG	0x1
#define INT_CP_FLAG	0x2
#define INT_MATCH_FLAG	0x4

volatile unsigned int * ef_tcc32_PERIOD_REG	= (volatile unsigned int *) EF_TCC32_PERIOD_REG_ADDR;
volatile unsigned int * ef_tcc32_COUNTER_MATCH_REG	= (volatile unsigned int *) EF_TCC32_COUNTER_MATCH_REG_ADDR;
volatile unsigned int * ef_tcc32_CONTROL_REG	= (volatile unsigned int *) EF_TCC32_CONTROL_REG_ADDR;
volatile unsigned int * ef_tcc32_RIS_REG	= (volatile unsigned int *) EF_TCC32_RIS_REG_ADDR;
volatile unsigned int * ef_tcc32_ICR_REG	= (volatile unsigned int *) EF_TCC32_ICR_REG_ADDR;
volatile unsigned int * ef_tcc32_IM_REG	= (volatile unsigned int *) EF_TCC32_IM_REG_ADDR;
