/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@aucegypt.edu)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define TCC_BASE				0x00000000

#define	TCC_TIMER_REG_ADDR		(TCC_BASE+0x0)
#define	TCC_PERIOD_REG_ADDR		(TCC_BASE+0x4)
#define	TCC_COUNTER_REG_ADDR		(TCC_BASE+0x8)
#define	TCC_COUNTER_MATCH_REG_ADDR		(TCC_BASE+0xc)
#define	TCC_CONTROL_REG_ADDR		(TCC_BASE+0x10)
#define	TCC_ICR_REG_ADDR		(TCC_BASE+0xf00)
#define	TCC_RIS_REG_ADDR		(TCC_BASE+0xf04)
#define	TCC_IM_REG_ADDR		(TCC_BASE+0xf08)
#define	TCC_MIS_REG_ADDR		(TCC_BASE+0xf0c)

#define TCC_CONTROL_REG_EN		0
#define TCC_CONTROL_REG_EN_LEN	1
#define TCC_CONTROL_REG_TIMER_EN		1
#define TCC_CONTROL_REG_TIMER_EN_LEN	1
#define TCC_CONTROL_REG_CP_EN		3
#define TCC_CONTROL_REG_CP_EN_LEN	1
#define TCC_CONTROL_REG_CLK_SRC		8
#define TCC_CONTROL_REG_CLK_SRC_LEN	4
#define TCC_CONTROL_REG_UP_DOWN		16
#define TCC_CONTROL_REG_UP_DOWN_LEN	1
#define TCC_CONTROL_REG_ONE_SHOT		17
#define TCC_CONTROL_REG_ONE_SHOT_LEN	1
#define TCC_CONTROL_REG_CP_EVENT		24
#define TCC_CONTROL_REG_CP_EVENT_LEN	2
#define INT_TO_FLAG	0x1
#define INT_CP_FLAG	0x2
#define INT_MATCH_FLAG	0x4

volatile unsigned int * tcc_timer	= (volatile unsigned int *) TCC_TIMER_REG_ADDR;
volatile unsigned int * tcc_period	= (volatile unsigned int *) TCC_PERIOD_REG_ADDR;
volatile unsigned int * tcc_counter	= (volatile unsigned int *) TCC_COUNTER_REG_ADDR;
volatile unsigned int * tcc_counter_match	= (volatile unsigned int *) TCC_COUNTER_MATCH_REG_ADDR;
volatile unsigned int * tcc_control	= (volatile unsigned int *) TCC_CONTROL_REG_ADDR;
