SIM-RTL:
	iverilog EF_TCC32_apb_tb.v ../../hdl/rtl/EF_TCC32.v ../../hdl/rtl/bus_wrapper/EF_TCC32_apb.v 
	./a.out

SIM-GL:
	iverilog EF_TCC32_apb_tb.v ../../hdl/rtl/EF_TCC32.v ../../hdl/gl/sky130/EF_TCC32_apb.gl.v ../../util/tech/sky130/sky130_hd.v
	./a.out
